name: Create KBCore (iOS)

on:
  push:
    tags:
      - "*.*.*"

  workflow_dispatch:

jobs:
  kbcore-publish:
    name: Create KBCore for iOS
    concurrency: "kbcore-publish-${{ github.repository }}"
    runs-on: macos-latest
    steps:

    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set Up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Create Package.swift file and XCFramework
      run: ./gradlew :kbcore:createSwiftPackage -PGIT_USER=${{ github.actor }} -PGIT_TOKEN=${{ secrets.SECRET_GITHUB_CODE }} -PGITHUB_REPO=${{ github.repository }}

    - name: Setup Git user
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Set current tag name as github env
      run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Commit necessary files
      run: |
        git pull origin main
        git checkout tags/${{ env.CURRENT_TAG }} -b "commit-package-swift-${{ env.CURRENT_TAG }}"
        git add Package.swift
        git commit -m "Package.swift for v${{ env.CURRENT_TAG }}"
        git push --set-upstream origin "commit-package-swift-${{ env.CURRENT_TAG }}"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.SECRET_GITHUB_CODE }}
        commit-message: "Package.swift for v${{ env.CURRENT_TAG }}"
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: commit-package-swift-${{ env.CURRENT_TAG }}
        delete-branch: false
        title: "Package.swift for v${{ env.CURRENT_TAG }}"
        assignees: ${{ github.actor }}
        reviewers: ${{ github.actor }}